development:
  adapter: mysql2
  encoding: utf8
  database: weseen_development
  username: root
  password: 
  host: localhost
  port: 3306
production:
  adapter: mysql2
  encoding: utf8
  database: weseen_production
  username: root
  password: 
  host: localhost
  port: 3306